config/routes.rb
App::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :players
  resources :pitches
   
  root to: 'static_pages#home'
  
  match '/update_order', to: 'players#update_order'
  match '/bench', to: 'players#bench'
  match '/active', to: 'players#active'
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
      
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if signed_in?
      @players_active = current_user.players.where(active: true).order(:order_num)
      @players_bench = current_user.players.where(active: false).order(:last_name)
    end
  end
  
  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>

app/views/static_pages/home.html.erb
<% if signed_in? %>

  <ul class="breadcrumb">
    <li class="active">Home</li>
    <li><%= link_to "Create a player", new_player_path %></li>
    <li><%= link_to "Stats", players_path %>
    
    <li class="pull-right"><%= link_to "Sign out", signout_path %></li>
  </ul>

  
  <h1>Active Players</h1>
  <table class="table table-striped">
    <th>Name</th>
    <th>Batting Position</th>
    <th></th>
    <th></th>
    <th></th>
    
    <% @players_active.each do |player| %>
    <tr>
      <td><%= link_to "#{player.name}", new_pitch_path(id: player.id) %></td> 
      <td><%= player.order_num %></td>
      <td><%= link_to "Up", update_order_path(id: player.id, direction: -1, order_num: player.order_num), method: :put %></td>
      <td><%= link_to "Down", update_order_path(id: player.id, direction: 1, order_num: player.order_num), method: :put %></td>
      <td><%= link_to "Move to Bench", bench_path(id: player.id), method: :put %></td>
    </tr>
    <% end %>
  </table>
  
  <h1>Bench Players</h1>
    <table class="table table-striped">
      <th>Name</th>
      <th></th>
      <% @players_bench.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <td><%= link_to "Make active", active_path(id: player.id), method: :put %></td>
      </tr>
      <% end %>
    </table>
  
  
  
  
  
<% else %>
  <h1>Softball Statistics Tracker and Analyzer</h1>

  <%= link_to "Sign up!", signup_path, class: "btn btn-large btn-primary" %>
  <%= link_to "Sign in!", signin_path, class: "btn btn-large btn-primary" %>
<% end %>